<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

    <material name="gripper_metal_grey">
        <color rgba="0.501960784313725 0.501960784313725 0.501960784313725 1"/>
    </material>
    <material name="gripper_metal">
        <color rgba="0.768627450980392 0.749019607843137 0.729411764705882 1"/>
    </material>

    <xacro:macro name="indy_two_finger_gripper" params="prefix parent_link tcp_offset_xyz">
        
        <xacro:property name="gripper_mass" value="0.5" />
        <xacro:property name="finger_length" value="0.10" />
        <xacro:property name="finger_width" value="0.015" />
        <xacro:property name="finger_depth" value="0.015" />
        <xacro:property name="gripper_body_length" value="0.06" />
        <xacro:property name="max_opening" value="0.08" />
        <xacro:property name="finger_spread" value="0.04" /> 
        
        <link name="${prefix}gripper_base_link">
            <visual>
                <origin xyz="0 0 ${gripper_body_length/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${gripper_body_length} ${finger_spread + finger_width*2 + 0.06} ${gripper_body_length}"/>
                </geometry>
                <material name="gripper_metal_grey"/> 
            </visual>
            <collision>
                <origin xyz="0 0 ${gripper_body_length/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${gripper_body_length} ${finger_spread + finger_width*2 + 0.06} ${gripper_body_length}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${gripper_mass}"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
            </inertial>
        </link>

        <joint name="${prefix}gripper_base_joint" type="fixed">
            <parent link="${prefix}${parent_link}"/>
            <child link="${prefix}gripper_base_link"/>
            <origin xyz="${tcp_offset_xyz}" rpy="0 0 0"/> 
        </joint>

        <link name="${prefix}left_finger_link">
             <visual>
                <origin xyz="0 ${finger_width/2} 0" rpy="0 0 0"/>
                <geometry><box size="${finger_depth} ${finger_width} ${finger_length}"/></geometry>
                <material name="gripper_metal"/>
            </visual>
            <collision>
                <origin xyz="0 ${finger_width/2} 0" rpy="0 0 0"/>
                <geometry><box size="${finger_depth} ${finger_width} ${finger_length}"/></geometry>
            </collision>
             <inertial>
                <mass value="0.1" />
                <origin xyz="0 0 0"/>
                <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
            </inertial>
        </link>

        <joint name="${prefix}left_finger_joint" type="prismatic">
            <parent link="${prefix}gripper_base_link"/>
            <child link="${prefix}left_finger_link"/>
            <origin xyz="0 ${finger_spread/2} ${gripper_body_length}"/>
            <axis xyz="0 1 0"/>
            <limit effort="100" lower="0.0" upper="${max_opening/2}" velocity="0.5"/>
            <safety_controller soft_lower_limit="0.0" soft_upper_limit="${max_opening/2}" k_position="100" k_velocity="1"/>
        </joint>

        <link name="${prefix}right_finger_link">
            <visual>
                <origin xyz="0 ${-finger_width/2} 0" rpy="0 0 0"/>
                <geometry><box size="${finger_depth} ${finger_width} ${finger_length}"/></geometry>
                <material name="gripper_metal"/>
            </visual>
            <collision>
                <origin xyz="0 ${-finger_width/2} 0" rpy="0 0 0"/>
                <geometry><box size="${finger_depth} ${finger_width} ${finger_length}"/></geometry>
            </collision>
            <inertial>
                <mass value="0.1" />
                <origin xyz="0 0 0"/>
                <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
            </inertial>
        </link>
        
        <joint name="${prefix}right_finger_joint" type="prismatic">
            <parent link="${prefix}gripper_base_link"/>
            <child link="${prefix}right_finger_link"/>
            <origin xyz="0 ${-finger_spread/2} ${gripper_body_length}"/>
            <axis xyz="0 -1 0"/> 
            <limit effort="100" lower="0.0" upper="${max_opening/2}" velocity="0.5"/>
            <safety_controller soft_lower_limit="0.0" soft_upper_limit="${max_opening/2}" k_position="100" k_velocity="1"/>
        </joint>

        <gazebo reference="${prefix}right_finger_joint">
            <mimic joint="${prefix}left_finger_joint" multiplier="1" offset="0"/>
        </gazebo>

    </xacro:macro>
</robot>